version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: web
    networks:
      app_net:
        ipv4_address: 172.20.0.5


  reverse-proxy:
    image: haproxy:latest
    container_name: reverse-proxy
    volumes:
      - ./haproxy/reverse/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8080:8080"
    networks:
      - app_net

  ingress-proxy:
    image: nginx:latest
    container_name: ingress-proxy
    network_mode: "host"
    volumes:
      - ./nginx/ingress/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - reverse-proxy

networks:
  app_net:
    external: true
    name: task_1_app_net
